version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/trand-rema
    command: ["/bin/sh", "-c", "chmod +x main.sh"]
    command: ["main.sh"]
    # command: ["python", "jmath.py"]
