version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "1007:1007"
    restart: always
    volumes:
      - .:/jmath
    command: ["sh", "-c", "chmod +x ./main.sh && ./main.sh"]
    # command: ["python", "jmath.py"]
