version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/trand-rema
    command: ["sh", "-c", "chmod +x ./main.sh && ./main.sh"]
    # command: ["python", "jmath.py"]
