from . import teor_handler_5_6
from . import konspekt_handler_6
from . import konspekt_handler_7
from . import konspekt_handler_8
from . import konspekt_handler_9
from . import konspekt_handler_10
from . import konspekt_handler_11
from . import konspekt_geometry_1
from . import konspekt_geometry_2
from . import konspekt_geometry_3
from . import konspekt_geometry_4