SAT_BOOKS = ["BQACAgIAAxkBAAIu7mPISqMOEPphy4-bK6bbNb9VsyGOAALBJQACGx5ISiSVOmzkPwwZLQQ", \
            "BQACAgIAAxkBAAIu8GPIStV61731kKCoxWuPUGqu9mbvAALEJQACGx5ISjHFhQsWpPlALQQ", \
            "BQACAgIAAxkBAAIu8mPISu-KzVaGERGjn6tNn37SYSbOAALFJQACGx5ISstvrxQzFu_4LQQ", \
            "BQACAgIAAxkBAAIu9GPISv0f7AlcBuj4ZO_RhHE-1Qh3AALGJQACGx5ISiX6OLBE9beKLQQ"]

GRE_BOOKS = ["BQACAgIAAxkBAAIw-mPJJmK62rSCj1ZAuAjjorMgfFwaAAKyKQACGx5ISiIkz3LAIzK7LQQ",\
             "BQACAgIAAxkBAAIw_GPJJy1oDWofzDyGWSjGkluSeF4wAAK4KQACGx5ISvTNaSn0am5WLQQ",\
             "BQACAgIAAxkBAAIw_mPJJ0NoUg6eswgoiuftDZhFygMcAAK5KQACGx5ISq_gwXr1xmZHLQQ",\
                "BQACAgIAAxkBAAIxAAFjySdXP3J-xHctcpgdWuKTvWcVtgACvSkAAhseSEoj_Aq7ny8BzS0E",\
                "BQACAgIAAxkBAAIxAmPJJ3xGu9yuiZWRBvbb5g37Bh4TAALAKQACGx5ISoChhJXfmsRmLQQ",\
                "BQACAgIAAxkBAAIxBGPJJ56fsyQa3GDyf3TJRhTx0E-AAALBKQACGx5ISjrKI9rbv10VLQQ",\
                "BQACAgIAAxkBAAIxBmPJJ8BzduISvmAiy2-A7ocu1jM3AALCKQACGx5ISnRJ0Nb5IdjDLQQ",\
                "BQACAgIAAxkBAAIxCGPJJ9rapSsLK-URV9JpNXgMy8F-AALEKQACGx5ISlJB2BUD4mxCLQQ",\
                "BQACAgIAAxkBAAIxCmPJJ_qUyNPWBhDZfiBEY9RT0Qg5AALGKQACGx5ISpS81rFwKK1XLQQ"]

GUBKIN_BOOKS = ["BQACAgIAAxkBAAIXDGMWR8U2Ub7IdactvGLL8EDXsEYSAALYHgAC1k2xSPwUpiUFcd2_KQQ", \
                 "BQACAgIAAxkBAAIXDmMWR969CrqnPrFlJKj5u6MI74slAALbHgAC1k2xSFdBIQXrK_gqKQQ", \
                 "BQACAgIAAxkBAAIXEGMWR_fa_WoncZ56nUfk11Qoho5ZAALdHgAC1k2xSM4cPHKxjf0CKQQ"]

AMITY_BOOKS = ["BQACAgIAAxkBAAIXFGMWSFeJBC7XxtqNFm26sXwR38LRAALkHgAC1k2xSK9-25dnPpHHKQQ", \
            "BQACAgIAAxkBAAIXEmMWSEIQHc1HwlmeivOmw4KlF5eEAALiHgAC1k2xSIOl75eRzhZmKQQ",\
            "BQACAgIAAxkBAAIXFmMWSGrdZltE6dfooY5_ubm12kVjAALlHgAC1k2xSNKDvAyFX27DKQQ", \
            "BQACAgIAAxkBAAIXGGMWSJUqvPbEPXJcDLNVnjC9RCZSAALoHgAC1k2xSGol-BmYgbCHKQQ",\
            "BQACAgIAAxkBAAIXGmMWSKxqdOHOqsGRYU0S9koqJdxHAALpHgAC1k2xSNmkUtZQ4D59KQQ",\
            "BQACAgIAAxkBAAIXHGMWSMC3OKhyuX2GZ6ovq0rQ3PfjAALsHgAC1k2xSIJ0hCxmIwijKQQ"]

IUT_BOOKS = ["BQACAgIAAxkBAAIXBWMWRu6uE2b3dj-19WFaGWJvrs1kAALJHgAC1k2xSLWBVSKnCcu5KQQ",\
             "BQACAgIAAxkBAAIXCGMWRw1ruCgHTvxrayaUV1sXjoPnAALLHgAC1k2xSEBk1I0Q26AhKQQ",\
             "BQACAgIAAxkBAAIXCmMWRyUVbJyMNl--t4sUAbeQOeFFAALMHgAC1k2xSKITag68hkmTKQQ",\
             "BQACAgIAAxkBAAIzoWPJS8VKy_piXdKYznxuQtOPNcj7AAKlIQACGx5QSro9tT3JYiRTLQQ",\
             "BQACAgIAAxkBAAIzo2PJS9oG0Rzpwcz9r8PXsfF2Txo8AAKmIQACGx5QSv5iUpXDPaMbLQQ",\
             "BQACAgIAAxkBAAIzpWPJS-r9OV20YmCectNRSAHl7lksAAKoIQACGx5QSvZVyXQxggcjLQQ", \
                "BQACAgIAAxkBAAIzp2PJS_neLer8_cr4irKNIxM0kMskAAKqIQACGx5QSqz69l1pMlu6LQQ",\
                "BQACAgIAAxkBAAIzqWPJTAWio_tDnd5PEJnQRS8OZNdpAAKsIQACGx5QSgis_xoL-kndLQQ",\
                "BQACAgIAAxkBAAIzq2PJTBJO6JV_WCkrw_AbZPQ-mc1wAAKtIQACGx5QShAP4x9kLlssLQQ",\
                "BQACAgIAAxkBAAIzrWPJTB80VmojP0N6d7Addrb7XXEEAAKuIQACGx5QSuH_8K94O2wFLQQ",\
                "BQACAgIAAxkBAAIzr2PJTCzP24khE2qwaIECJQXlqhP8AAKvIQACGx5QSoOIJvLnillHLQQ",\
                "BQACAgIAAxkBAAIzsWPJTDjmpwVbA_kh2eKd8bCblh6XAAKwIQACGx5QSvoP1jU2aTlELQQ",\
                "BQACAgIAAxkBAAIzs2PJTEt71qZDeczdN06G_sA0WYlFAAKzIQACGx5QSnS6d7KBJrdDLQQ",\
                "BQACAgIAAxkBAAIztWPJTGX7RFRWRS9UXFlLKugLa1JTAAK2IQACGx5QSkkuMlJeEv7PLQQ",\
                "BQACAgIAAxkBAAIzt2PJTHQlsMkeUPBEJDwY4yIol6zdAAK3IQACGx5QSv6jP-ygp4VHLQQ",\
                "BQACAgIAAxkBAAIzuWPJTIDJmD4f72CUB2QFgYBu__FfAAK5IQACGx5QSmf5eYvtrf32LQQ"]

INTERHOUSE_BOOKS = ["BQACAgIAAxkBAAI65GPVW-fdbA5Efeio867-dYn6KZMDAAIkKAACRF2pSrXrlO4cZyE_LQQ",\
                "BQACAgIAAxkBAAI65mPVW_4GNrJe74S6KknEMJKfhHE2AAIoKAACRF2pSlNqOevFrdHFLQQ", \
                "BQACAgIAAxkBAAI66GPVXAol3CkjxSNgdZfx1g2WCfi7AAIpKAACRF2pSumgNuCQoIo2LQQ",\
                "BQACAgIAAxkBAAI66mPVXBQHphLj_NWIDtGQK-eIyCyRAAIrKAACRF2pSkosSJ64gOJWLQQ",\
                "BQACAgIAAxkBAAI67GPVXCAwemOSBDYdWFVz5n_RiXojAAIsKAACRF2pSq1rI4iqXytYLQQ",\
                "BQACAgIAAxkBAAI67mPVXCoV1r-iTRePb2l5jK0oQpLKAAItKAACRF2pSnL8KeY212nhLQQ",\
                "BQACAgIAAxkBAAI68GPVXDYx047RPYlxH6tAYjT0C8aDAAIvKAACRF2pSoVdy57p1szGLQQ",\
                "BQACAgIAAxkBAAI682PVXEaFSZs8pSVz2pbDb5mkaF7OAAIwKAACRF2pSkm8beh-RgSwLQQ",\
                "BQACAgIAAxkBAAI69WPVXFKQTHaa0dRV9a-KPE-syK8XAAIyKAACRF2pSjujJeoD0-0WLQQ",\
                "BQACAgIAAxkBAAI692PVXF0KLdsTDI8-e2Uhs8ZKFxe6AAI2KAACRF2pSr06ewl7Kc8ULQQ",\
                "BQACAgIAAxkBAAI6-WPVXGjNCad6B5qM9pez7Cb5yoU4AAI3KAACRF2pSsXOKLQfwPjHLQQ",\
                "BQACAgIAAxkBAAI6-2PVXHUnOagjX7Qon-Rlj2MraQkSAAI5KAACRF2pSkhXOqAXOI9XLQQ",\
                "BQACAgIAAxkBAAI6_WPVXIQqx_Z9cxjZQJSL6vuRcT29AAI6KAACRF2pSiPjXugMm-eRLQQ",\
                "BQACAgIAAxkBAAI6_2PVXI7uW54wpoXslbLRLFbahGN8AAI8KAACRF2pSivPZzD5GIscLQQ",\
                "BQACAgIAAxkBAAI7AWPVXJqK0wE9brTvVMeO14WALp3ZAAI-KAACRF2pStvwbRgi9q9QLQQ",\
                "BQACAgIAAxkBAAI7A2PVXKYmLdKR-QtPxgw3CURMM9k9AAJAKAACRF2pSnyYB7nLXkuNLQQ",\
                "BQACAgIAAxkBAAI7BWPVXLC_tzEscsMGwnfXhuz9B9N7AAJBKAACRF2pSmuyhiqZDeoKLQQ",\
                "BQACAgIAAxkBAAI7B2PVXLy-ECSlr7WJjvMDgmJRyBWYAAJDKAACRF2pSiYMLUv6zrRCLQQ",\
                "BQACAgIAAxkBAAI7CWPVXMd54s29e-ZoSnx41nbCh4P9AAJEKAACRF2pSnRQ-m1134hmLQQ",\
                "BQACAgIAAxkBAAI7C2PVXNFxjw1YUBb3BzA2Ns3FSEODAAJHKAACRF2pSoWd2qomboemLQQ",\
                "BQACAgIAAxkBAAI7DWPVXNoGuVwFkcnz2vBEtvNXX-lFAAJJKAACRF2pSpIX1fjFXVfyLQQ",\
                "BQACAgIAAxkBAAI7D2PVXOQ0MQTLxai07_TL3BqKP0IlAAJKKAACRF2pSvpp3512b4nPLQQ",\
                "BQACAgIAAxkBAAI7EWPVXO1Kr_2E63sGcFfKsw6Ml-JlAAJLKAACRF2pSiJm9ptwMfuULQQ",\
                "BQACAgIAAxkBAAI7E2PVXPbJdUrxJTs1TFRFg8rxsyqGAAJNKAACRF2pSvdTLWT3GmBmLQQ",\
                "BQACAgIAAxkBAAI7FWPVXQEH-XwcaTw5znJckjlh4CN6AAJOKAACRF2pSqtxg-yyyraMLQQ",\
                "BQACAgIAAxkBAAI7F2PVXQumiWsSjJYSLFkE-tm1Z2fbAAJPKAACRF2pSg24E9LGrMZILQQ",\
                "BQACAgIAAxkBAAI7GWPVXRaCKEsTxmbHchFVYGqhNePSAAJQKAACRF2pSsrV_rpiW9ODLQQ",\
                "BQACAgIAAxkBAAI7G2PVXSYYouDeJvVQ9K8sQf-IgIH9AAJSKAACRF2pSsg0xcobvPTlLQQ",\
                "BQACAgIAAxkBAAI7HWPVXTBIpAyTWP9w5NAsBliVnO4lAAJTKAACRF2pSkCmyygvHbmxLQQ",\
                "BQACAgIAAxkBAAI7H2PVXTvqMdaGcgS_EMWLLeE5kX0yAAJUKAACRF2pSpL1Z5_mbt3bLQQ"]

MIFI_BOOKS = ["BQACAgIAAxkBAAIzu2PJTM1bMf5LWkvlWhGj-9OPFJvkAAK8IQACGx5QSnz6oEC_qMhOLQQ"]

PLEHANOVA_BOOKS = ["BQACAgIAAxkBAAIzw2PJTV60NS4AAUI35WavolpcEm56GAACxyEAAhseUErrqSQMCuWTRi0E",\
                "BQACAgIAAxkBAAIzxWPJTXR3ncokJ0IxoOJjrqxYMyYYAALKIQACGx5QSmb0z1UkDv-YLQQ",\
                "BQACAgIAAxkBAAIzx2PJTYCkriGFhqWCKB8MkBfKO_PBAALLIQACGx5QShKXg1UzER5pLQQ",\
                "BQACAgIAAxkBAAIzyWPJTY_nTu_lD8TOx4HMj90iF-4UAALMIQACGx5QSsk1KPw7CWu-LQQ",\
                "BQACAgIAAxkBAAIzy2PJTZru-1dBKP11uz5-hKmyu4DmAALNIQACGx5QSmzGB7hrUQb0LQQ"]

MGU_BOOKS = ["BQACAgIAAxkBAAIzzWPJTcXNG2ELzMYt_OfZPvlkei2tAALRIQACGx5QSstCHCkbvFiJLQQ",\
        "BQACAgIAAxkBAAIzz2PJTdIIr0qvC8K1xU0sb09WL-71AALSIQACGx5QSl7U-GzgiV6hLQQ",\
        "BQACAgIAAxkBAAIz0WPJTeBhRd0t1cvHf4d7oNQUJI1mAALTIQACGx5QSs7LD0alwdubLQQ",\
        "BQACAgIAAxkBAAIz02PJTet2HXDETCpXL1L2iT9RZ7cKAALUIQACGx5QSndyZTwFEub1LQQ"]

WIUT_2015_BOOKS = ["BQACAgIAAxkBAAIXjWMW0fq1E9PpJaFE6AlrU6I-4tKDAALnGgAC1k25SBMi-loP2ky5KQQ",\
                    "BQACAgIAAxkBAAIXj2MW0lKkwoPOyVOjr0nuHRwdZd0sAALpGgAC1k25SH_p3Qx8kNSaKQQ",\
                    "BQACAgIAAxkBAAIXkWMW0oHLn5KCNiEDFOXWS4yfwmBxAALqGgAC1k25SMP7oqd9bepBKQQ",\
                    "BQACAgIAAxkBAAIXk2MW0qDRVON8WezVgAszK3HCY_NRAALsGgAC1k25SMwNwlUeDgf-KQQ"]

WIUT_2018_BOOKS = ["BQACAgIAAxkBAAIXiWMW0Ycwun0u3YEK17fno6ukW_OmAALjGgAC1k25SF0XHw9RmkyoKQQ",\
                    "BQACAgIAAxkBAAIXi2MW0cbAuRc-PuI_tryayhx3fBIUAALlGgAC1k25SLEOp-k-soVhKQQ"]

WIUT_2019_BOOKS = ["BQACAgIAAxkBAAIXlWMW0sF8lW1ZYTK5BOzNWQuz9bixAALtGgAC1k25SK-wYNsWjai3KQQ",\
                    "BQACAgIAAxkBAAIXl2MW0ugPBw8-Rtg4CNf4myXNOZYUAALvGgAC1k25SLcfXUT6yitDKQQ",\
                    "BQACAgIAAxkBAAIXmWMW0wOBEj8WQlGa8yrOr2byx-8-AALwGgAC1k25SKAdz1igckYPKQQ",\
                    "BQACAgIAAxkBAAIXm2MW0y7w3zjAEOzE3umLeGRrBOMIAALxGgAC1k25SPllTHN9EGm4KQQ",\
                    "BQACAgIAAxkBAAIXnWMW04Hb3ItSLmXmNa7wEf61j1bAAALyGgAC1k25SLgbkJuExlOUKQQ",\
                    "BQACAgIAAxkBAAIXn2MW05X9mx2uSwefTj9RhzRGfuhxAALzGgAC1k25SGZg4Pv3c_hAKQQ",\
                    "BQACAgIAAxkBAAIXoWMW09PH78BlDvJQjOXI4WIkIvyhAAL0GgAC1k25SHwyV9UYVBGpKQQ",\
                    "BQACAgIAAxkBAAIXo2MW0_KVblZyahVO7inifOVDxGFcAAL1GgAC1k25SHPAeurWBY6bKQQ"]

WIUT_2020_BOOKS = ["BQACAgIAAxkBAAIXpWMW1C1RufqUtglWgpOAhcdHw6EtAAL3GgAC1k25SNCDupd6AAEb0ikE",\
                    "BQACAgIAAxkBAAIXp2MW1EsSi5jMv7TCSV_mal4iMrTFAAL4GgAC1k25SMxl03oQEk0bKQQ",\
                    "BQACAgIAAxkBAAIXqWMW1G91tfAYzI45EAh_hvY8w1McAAL5GgAC1k25SPyRW5GEqpQKKQQ",\
                    "BQACAgIAAxkBAAIXq2MW1INF9tfCSxzdIMWx1Y1aXwcHAAL6GgAC1k25SN49lJQDOrVzKQQ",\
                    "BQACAgIAAxkBAAIXrWMW1JSaAfA-53SllgYpHPj1j294AAL7GgAC1k25SM7og3EIiliMKQQ",\
                    "BQACAgIAAxkBAAIXr2MW1KSX_EwvSsMZhnhh0Ahk6QQVAAL8GgAC1k25SP_ETP0uNEJ5KQQ",\
                    "BQACAgIAAxkBAAIXsWMW1Lku-vWtPfmfSJ2XUvC5BtJoAAL9GgAC1k25SIt1t48OiiGVKQQ"]

WIUT_L_2015_BOOKS = ["BQACAgIAAxkBAAIaN2MiEUeJ0U5Mmh44vhM_hUOvvVgSAAI3IQAC67URSTFQ4ZiEtXvGKQQ",\
                    "BQACAgIAAxkBAAIaOWMiEZwTPAABKssIYew-SOkQMPWLnwACPCEAAuu1EUnCvneOG1s2TSkE",\
                    "BQACAgIAAxkBAAIaO2MiEcvETe8dgKzyXKNLbfjZuYxcAAI9IQAC67URSR5l40iR-Q6BKQQ",\
                    "BQACAgIAAxkBAAIaPWMiEe6nfXzt1KP97wq4WMhv3EqGAAI_IQAC67URSd7mSOUOXlb5KQQ",\
                    "BQACAgIAAxkBAAIaP2MiEhG26phdvykDuEVmaGrpmbsJAAJBIQAC67URSZTSd19XfesxKQQ",\
                    "BQACAgIAAxkBAAIaQWMiEjPag81JPU2ko7vJBltyeXogAAJCIQAC67URScVuFRL_vkQfKQQ"]

WIUT_L_2018_BOOKS = ["BQACAgIAAxkBAAIXs2MW1Xs6KKQpTdD672GzGwebN8MVAAMbAALWTblI6zDaohxe74ApBA"]

WIUT_L_2019_BOOKS = ["BQACAgIAAxkBAAIaR2MiEyKMq-UXOu3RVeaQw50djJkoAAJGIQAC67URSUmaukj3Y5BRKQQ",\
                     "BQACAgIAAxkBAAIaSWMiE07a6SzDA054ckc1v70InlvnAAJIIQAC67URSWsJiA0gKNi_KQQ"]

WIUT_L_2021_BOOKS = ["BQACAgIAAxkBAAIaS2MiE4EFbkd3ZKnzFYxDRzdunJswAAJLIQAC67URSTvqwNpmyc7dKQQ"]

CAMBRIDGE = ["BQACAgIAAxkBAAIVqmMVoQF3Y12RM4sg4hRv7yb3xUedAAL0HgACH8OpSInG3V4NqwmYKQQ",\
            "BQACAgIAAxkBAAIVvWMV2wdW0U2TSmYbl35mWv_1I3yWAAKpHwACH8OxSEiwZxPsPKCjKQQ",\
            "BQACAgIAAxkBAAIVv2MV2zwlmWu6-kPG1uYNLJK15pxjAAKqHwACH8OxSI1g0GmxMd8XKQQ",\
            "BQACAgIAAxkBAAIVwWMV23qP9nVCsKPyrhCL2wnWqP_mAAKrHwACH8OxSNPRFD-tv_jXKQQ",\
            "BQACAgIAAxkBAAIVw2MV25NT3l4afPqs5s_hqoOPgF1eAAKtHwACH8OxSL4lvG7c5YgxKQQ",\
            "BQACAgIAAxkBAAIVxWMV28imiEkMKb3RAfReLUrktVaoAAKuHwACH8OxSPgMr5RXE9XoKQQ",\
            "BQACAgIAAxkBAAIVu2MV2t9QTB7KDK58M9wbC5WOIJwBAAKkHwACH8OxSMMlAfbkg7faKQQ", \
            "BQACAgIAAxkBAAIVx2MV2_jTemEbhepa4Tb2_gABfNJLDQACrx8AAh_DsUgHifvVe5E89ykE",\
            "BQACAgIAAxkBAAIVyWMV3BraXZS1Xtc9PYYAAUvBounWywACsB8AAh_DsUg9vpVdie_YwCkE"]

SKANAVI = ["BQACAgIAAxkBAAIV8mMWOJRG9jsiqPFLb-aDx0UfEcthAAIvHgAC1k2xSOtSHR0LByTVKQQ",\
            "BQACAgIAAxkBAAIV9GMWOLi8OLDww7Qa6zay3sqtpGSuAAIyHgAC1k2xSBvuIMTFL6JLKQQ",\
            "BQACAgIAAxkBAAIV9mMWONlpe2ZlWW_5I8GkkzPIY4ozAAI1HgAC1k2xSDJlI-6ICPK-KQQ",\
            "BQACAgIAAxkBAAIV-GMWOXdK0iCy8IbL8BpnyXrrAAGJqgACPx4AAtZNsUjSClw6koyC6SkE", \
            "BQACAgIAAxkBAAIV8GMWOBZv4oQfzgQWVKJyXNpvs7tdAAIkHgAC1k2xSEff_xaR_nKsKQQ"]

USMONOV = ["BQACAgIAAxkBAAIWBmMWO7vYhEKL59knk3j0pcJRfSklAAJaHgAC1k2xSBO0QsFL-j_TKQQ",\
            "BQACAgIAAxkBAAIWCGMWO-qM74mOA85bF9CH_NrpBbeKAAJeHgAC1k2xSDrxDfggbpeUKQQ",\
            "BQACAgIAAxkBAAIWYGMWQamlV3N2X5k1I17uv1I95xrlAAKDHgAC1k2xSBHOzp15WUTGKQQ"]

SCHOOL_BOOKS = ["BQACAgIAAxkBAAIWbGMWQ2PvTOrHWn0oQZf-7zACqVKfAAKXHgAC1k2xSIbU0_BtxOPXKQQ",\
                "BQACAgIAAxkBAAIWbmMWQ9nMnrmaCtIosd1mBGKh0XB4AAKcHgAC1k2xSHmJ_Kx1oO0iKQQ",\
                "BQACAgIAAxkBAAIWcGMWRA8xaNb6ZocqLKOAp-JP_EFHAAKdHgAC1k2xSMKN-UYEdhY-KQQ",\
                "BQACAgIAAxkBAAIWcmMWRETsSrcLy3vxLtNQ6Gli1xy-AAKhHgAC1k2xSFF1O4xN3f4rKQQ",\
                "BQACAgIAAxkBAAIWdGMWRHLEqFCkZFL3-I84IpCpRpN0AAKiHgAC1k2xSOz8tdYd4dJlKQQ",\
                "BQACAgIAAxkBAAIWdmMWRJ7BhSOCOmhjFIVbibuKoQ50AAKlHgAC1k2xSOMnCKmgi8joKQQ",\
                "BQACAgIAAxkBAAIWeGMWRNC_s8vWVv0aMKkP3WhtRhMnAAKrHgAC1k2xSEwROFGQxxpmKQQ",\
                "BQACAgIAAxkBAAIWemMWRQYysQJqlc_2huSgiAva-fAeAAKtHgAC1k2xSFUUNF0IUhhJKQQ"]

SHARIGINA = ["BQACAgIAAxkBAAIV-mMWOffHgpbVNcyTqd5LB0l0U4NnAAJEHgAC1k2xSCcsl3AJa7nuKQQ",\
            "BQACAgIAAxkBAAIV_GMWOg79qnYY6BGQj8DZJNnPKvmYAAJGHgAC1k2xSLZlTfInS8psKQQ",\
            "BQACAgIAAxkBAAIV_mMWOitJkfSjcOW3cA70G8y4_RbnAAJIHgAC1k2xSEfpf7xmlUc4KQQ",\
            "BQACAgIAAxkBAAIWAAFjFjpP7gUfCZ486U_-eSyooK5BfgACSx4AAtZNsUhY-oTfBaJ7aykE",\
            "BQACAgIAAxkBAAIWAmMWOmtEI2aiVf6sziIjk_m584u4AAJMHgAC1k2xSMZMu1zhCJ6fKQQ",\
                    "BQACAgIAAxkBAAIWBGMWOo3_ovkeMowUwNMzCYXNxPqqAAJPHgAC1k2xSM15mWqwGuvKKQQ"]

TRENAJOR = ["BQACAgIAAxkBAAIWCmMWPENKnjc7hY3_75HmUgGapxwrAAJgHgAC1k2xSD9L8uxU9_m8KQQ"]

SBORNIK = ["BQACAgIAAxkBAAIWVWMWQGa0BX7J29nyI1w-jj7lLQkUAAJ9HgAC1k2xSOhNlflKN6sxKQQ",\
            "BQACAgIAAxkBAAIWrmMWRbWgBpS8VeD0ZYu83dj_EerxAAK4HgAC1k2xSJTvzjXifrQiKQQ",\
            "BQACAgIAAxkBAAIWDGMWPMGYaZG44Uf7AqhW6LmgYVc4AAJkHgAC1k2xSEIAAcvFybgnjykE",\
            "BQACAgIAAxkBAAIWDmMWPPPGef7OPyWJ02jPQvvMZ1roAAJmHgAC1k2xSEp66DWQdfHCKQQ",\
            "BQACAgIAAxkBAAIWXGMWQMIhQwt4uJyJeknEuGh58pywAAJ-HgAC1k2xSC4_BLK4AAGyrikE",\
            "BQACAgIAAxkBAAIWXmMWQRxD6k6NeEkXsU_ZVFis5fNfAAKBHgAC1k2xSKZoXFvDm5uoKQQ"]

MEDIC = ["BQACAgIAAxkBAAIWEGMWPRL9CJruGOtZASs-cUfJ4LTPAAJnHgAC1k2xSFByjtq1EUq-KQQ"]

LOGICAL = ["BQACAgIAAxkBAAIWYmMWQdvrQnL3mIkHuLWDe_tMREogAAKGHgAC1k2xSCTuXueaRUr5KQQ",\
            "BQACAgIAAxkBAAIWZGMWQhl-OG0qn7xEp2wh6dQ0QxY4AAKHHgAC1k2xSOF1l9-yYauxKQQ",\
            "BQACAgIAAxkBAAIWaGMWQoGRYggCW6WnNSCE-u-b7QwYAAKMHgAC1k2xSLYAATBphIKwGikE",\
            "BQACAgIAAxkBAAIWamMWQqkWhrdXQUc46jUEGzvm0VUCAAKPHgAC1k2xSJwoV0DQfyonKQQ",\
            "BQACAgIAAxkBAAIWZmMWQktC8ZACKXNmhOWezUUFVMGCAAKIHgAC1k2xSNWNpjnv6BTQKQQ",\
            "BQACAgIAAxkBAAJBY2Q-3uxA9P_12cagtdJBKgvpMscXAALdLQAC5tb5ST7NWOy_bXnRLwQ",\
            "BQACAgIAAxkBAAJBZ2Q-3yI9Bf3QunYv7vs9BEeP24ckAALlLQAC5tb5SaA2yYBfFjy-LwQ",\
            "BQACAgIAAxkBAAJBaWQ-30NR8T254Hywivw07eAaLXY3AALoLQAC5tb5SccY58JZyWkpLwQ",\
            "BQACAgIAAxkBAAJBbWQ-32peV8FDiW-kPYblrgSBLrXlAALsLQAC5tb5SWmNQYv8kFWkLwQ",\
            "BQACAgIAAxkBAAJBbWQ-32peV8FDiW-kPYblrgSBLrXlAALsLQAC5tb5SWmNQYv8kFWkLwQ",\
            "BQACAgIAAxkBAAJBcWQ-35KCkG61PKmmY5ChmuTHzOumAALxLQAC5tb5SU9Qn-tomwztLwQ",\
            "BQACAgIAAxkBAAJBc2Q-36Q9WE-NDw2JDyt0qRqba2wwAALzLQAC5tb5STZc2yr0rClTLwQ"]

KONS_PARALLELOGRAM = ["BQACAgIAAxkBAAIdO2Mxm8VBk3trZG9_gwIt36RchyfaAAJeHwACiCmJSbvs6vRHEPLzKQQ"]

EGE = ["BQACAgIAAxkBAAIvyGPIWRi4GQWlUdCZFhK2kDXcK1VAAAI3JgACGx5IShn539HHXLS-LQQ", \
        "BQACAgIAAxkBAAIvymPIWSUrmCjp6CZYqXf4HuiqoHS9AAI4JgACGx5ISgX8Ro8_8_PZLQQ", \
        "BQACAgIAAxkBAAIvzGPIWTwncLVJfRU0eT-EQym_0zocAAI5JgACGx5ISpH8zIAb64sfLQQ", \
        "BQACAgIAAxkBAAIvzmPIWVYrSM-o3ViBVFlGQuKUiYMKAAI6JgACGx5ISi42kmuJKFXMLQQ", \
        "BQACAgIAAxkBAAIv0GPIWXzR45r8nhhKzLhh1LDHGjaGAAI7JgACGx5ISsyazqPa4FhkLQQ", \
        "BQACAgIAAxkBAAIv0mPIWYduJNzLDjEkUl042PTOozt2AAI8JgACGx5ISpTNZgABe-Q-XS0E", \
        "BQACAgIAAxkBAAIv1GPIWZdQp_M-UoA_tv6PqUuUZEGqAAI-JgACGx5ISirtUV7UYwE-LQQ", \
        "BQACAgIAAxkBAAIv1mPIWalV5sKs8RKNJO85tSIaUbLOAAI_JgACGx5ISk39AmmP3jkjLQQ", \
        "BQACAgIAAxkBAAIv2mPIWeUGQsvzCGBpWUMF4XYHQzMNAAJBJgACGx5ISr0UBVEmZyyTLQQ", \
        "BQACAgIAAxkBAAIwb2PI7Qxweu8poWli1DZu3rEenKc4AAKjJwACGx5ISkWhaahAD9piLQQ",\
        "BQACAgIAAxkBAAIwcWPI7V9Iw55zAzZL3kA4bTVIiq5PAAKlJwACGx5ISjCzYwABcM2EFC0E",\
        "BQACAgIAAxkBAAIwc2PI7YswE9NuPknNNi4NtJ7YaXLBAAKmJwACGx5ISmowiQrbIh1-LQQ", \
        "BQACAgIAAxkBAAIwdWPI7aANRMEkuVjzRNHxFDQ90lztAAKnJwACGx5ISizPk-GEXm8iLQQ",\
        "BQACAgIAAxkBAAIwd2PI7cLX3G81WQ-6LwGcnMMmbO6ZAAKoJwACGx5ISo6tjM7smQABFS0E",\
        "BQACAgIAAxkBAAIweWPI7dxvkd5_DXLjqoLOf1vgOZX4AAKpJwACGx5ISk4tyGH0f2iuLQQ",\
        "BQACAgIAAxkBAAIwe2PI7gOpklkY_cH8koh9EWZSOPeFAAKqJwACGx5ISpwdmj3BAhOKLQQ",\
        "BQACAgIAAxkBAAIwfWPI7jIWL_3SpvVotUXHTxyqz4MxAAKrJwACGx5ISv0yyK0ECW4NLQQ",\
        "BQACAgIAAxkBAAIwfWPI7jIWL_3SpvVotUXHTxyqz4MxAAKrJwACGx5ISv0yyK0ECW4NLQQ",\
        "BQACAgIAAxkBAAIwgWPI7oBVyLu6azNRscFtQ09erVvpAAKuJwACGx5ISpKwOqYYC-t8LQQ",\
        "BQACAgIAAxkBAAIwg2PI7o0sMrBlun1-R5xUTLeID7ZYAAKvJwACGx5ISnAGoCq6gLTZLQQ",\
        "BQACAgIAAxkBAAIwhWPI7qQ_-x77CpZjQtIOYC_N8Vh5AAKwJwACGx5ISvtjq3OhQQ6VLQQ",\
        "BQACAgIAAxkBAAIwh2PI7rBGia6LUlp02pdJZOwzDZLLAAKxJwACGx5ISq4WLeI-4vrILQQ",\
        "BQACAgIAAxkBAAIwh2PI7rBGia6LUlp02pdJZOwzDZLLAAKxJwACGx5ISq4WLeI-4vrILQQ",\
        "BQACAgIAAxkBAAIwi2PI7sq6-e3NSGrOggi2bRDs28ppAAKzJwACGx5ISjUF5jNs8vhqLQQ", \
        "BQACAgIAAxkBAAIwjWPI7tiX3G043QZO3ZDIi2px1cuYAAK1JwACGx5ISpe2_lYG7nARLQQ",\
        "BQACAgIAAxkBAAIwkWPI7w4DFvk0zv1qnTDwp7uc0IBmAAK2JwACGx5ISvNGZJkbNXQ8LQQ",\
        "BQACAgIAAxkBAAIwk2PI7y7IuPngNltnnsjX7RD-Sx4tAAK4JwACGx5ISuFwZVpUb-_BLQQ",\
        "BQACAgIAAxkBAAIwlWPI70K76_WmtqAUcqqw1Xvc1EV_AAK5JwACGx5ISlI-9a3s_tf8LQQ",\
        "BQACAgIAAxkBAAIwl2PI71CxiS5hg-kHInOzqJQYodV4AAK6JwACGx5ISq94gRQWPDM-LQQ",\
        "BQACAgIAAxkBAAIwmWPI718E6wQdDZSVx6f2qI7OWQ5eAAK7JwACGx5ISlU2NkXEqiIvLQQ",\
        "BQACAgIAAxkBAAIwnmPI73vIum2bhK5HhFtrz5N3pMQfAAK8JwACGx5ISvJ-z2MpaUnbLQQ",\
        "BQACAgIAAxkBAAIwoGPI75q-XF8SBXLDi1C-1jXGrCAYAAK9JwACGx5ISlH8azZjBLqZLQQ",\
        "BQACAgIAAxkBAAIwomPI76akEFuHBphn5DcGmtFTHSQaAAK_JwACGx5ISpSAL_vMrhaILQQ",\
        "BQACAgIAAxkBAAIwpGPI77OyXRliWGFhgHftKKxuTGYQAALBJwACGx5ISjtPL4Tkk55iLQQ",\
        "BQACAgIAAxkBAAIwpmPI78KtOcvN5nVPBCOEH6ecp0u6AALCJwACGx5ISjWwBVenwyT_LQQ",\
        "BQACAgIAAxkBAAIwqGPI79OLO1YRdFW6rGwYqsry4tBhAALDJwACGx5ISpxYAAF0Zfznai0E",\
        "BQACAgIAAxkBAAIwqmPI7-YIDlTAdq-d3JPCRRcdO9XIAALEJwACGx5ISreOTpUz2DjuLQQ",\
        "BQACAgIAAxkBAAIwrGPI7_ISGZkqxW3TVW26zcABnFIAA8YnAAIbHkhKF70Bjaj4BbstBA",\
        "BQACAgIAAxkBAAIwrmPI7_32ZuQS96O8IGanN-T6aEAAA8cnAAIbHkhKDQ1JNtc4DJMtBA",\
        "BQACAgIAAxkBAAIwsGPI8AhNjtii6vAfMox7PtzFTce2AALJJwACGx5ISjxyBDsfqm56LQQ",\
        "BQACAgIAAxkBAAIwsmPI8BMzLsC6lB2IGbsesKC0fmYkAALKJwACGx5ISumKUFq6lxqpLQQ",\
        "BQACAgIAAxkBAAIwtGPI8B7_8ri84foXipD4iwSQ8oVTAALLJwACGx5ISj0fNEWXaXivLQQ",\
        "BQACAgIAAxkBAAIwtmPI8C43p_YSse3Xjl1wK67iYTTeAALMJwACGx5ISp-6A4tv3k5pLQQ",\
        "BQACAgIAAxkBAAIwuGPI8EJ4c7y-Tuwts9YVa2cZmoqMAALNJwACGx5ISqJ_bK-nQlcJLQQ",\
        "BQACAgIAAxkBAAIwumPI8FFosev8w_2xMjw5vYuXS1eSAALOJwACGx5ISr0trvQM4t7BLQQ",\
        "BQACAgIAAxkBAAIwvGPI8F22tFKIFQ0bZ0sWMxVmrzFDAALPJwACGx5ISksyQoozz59kLQQ",\
        "BQACAgIAAxkBAAIwvmPI8GjVEDlZTU41vR_T1b17qpCTAALRJwACGx5ISpaS7FIWCra-LQQ",\
        "BQACAgIAAxkBAAIwwGPI8HTcL1VSPBnBAcS5Ik-39GwsAALSJwACGx5IStoE3gABHZQ8Ci0E",\
        "BQACAgIAAxkBAAIwwmPI8IBZ3_gdPHK-5Uk7iAUIbN3rAALUJwACGx5ISvBokxIqQJ-ALQQ",\
        "BQACAgIAAxkBAAIwxGPI8IxulV5logSa9JOEE3TsrNTWAALVJwACGx5IStgVRswQZGhSLQQ",\
        "BQACAgIAAxkBAAIwxmPI8JpIpixw9aX_7YsO2B3JT0yOAALWJwACGx5ISj_OMC-ZFcFoLQQ",\
        "BQACAgIAAxkBAAIwyGPI8KVP-2QJOH2J9-siDbLrszvXAALXJwACGx5ISv3YYVau5AEVLQQ",\
        "BQACAgIAAxkBAAIwymPI8LI0ptgR6w-QcfizxqV2TR3OAALYJwACGx5ISlvahePZt7hCLQQ"]

OGE = ["BQACAgIAAxkBAAIv3GPIWmX_jrRGBu6oMHxds5w_tMMXAAJGJgACGx5ISjYYVu1Ufv42LQQ", \
        "BQACAgIAAxkBAAIv3mPIWnmSgbyi2B-U2E8IjshGn0T0AAJHJgACGx5ISkPOR1D0c9IgLQQ", \
        "BQACAgIAAxkBAAIv4GPIWpLvwzHKap6zcWyBhMtlbMUwAAJIJgACGx5ISkBRO5d4zn35LQQ", \
        "BQACAgIAAxkBAAIv4mPIWq89UPYrILHhKi-TUEbTGeGFAAJJJgACGx5ISvon6C_UQLkZLQQ", \
        "BQACAgIAAxkBAAIv5GPIWr_x_0dHOJ38idspn1qIkA6NAAJKJgACGx5ISoj-VbWT3aJcLQQ"]

GMAT_BOOKS = ["BQACAgIAAxkBAAIu9mPIS2QN1gOwpqieaKM4-a7v8ICwAALKJQACGx5IShjgl8KY-uMdLQQ",\
              "BQACAgIAAxkBAAIwzmPI85G2c1szbzv9y4UUhQe0PRnHAALyJwACGx5ISguaEbi8SySCLQQ",\
              "BQACAgIAAxkBAAIw0GPI88jvxUvKLNtdOPe8cDucAAHIBQAC9ScAAhseSEox42zMEVL5Ti0E",\
                "BQACAgIAAxkBAAIw0mPI89YB7nMIQoRj6fJ4geBrv-YAA_YnAAIbHkhKAWwxxR-YF4stBA",\
                "BQACAgIAAxkBAAIw1mPI9KV5wZkt8ncO14DmaNHgSobRAAL-JwACGx5ISsRjKA0nNiLNLQQ",\
                "BQACAgIAAxkBAAIw2GPI9LwIY95VCODq18nn82ZR7RcWAAL_JwACGx5ISoWidIHe6zHLLQQ",\
                "BQACAgIAAxkBAAIw2mPI9M5HM429M4O_gKTaTOnjb-XnAAMoAAIbHkhKMNsMRFe-raItBA",\
                "BQACAgIAAxkBAAIw3GPI9N2HEGlir1setQLMzBHmYOzIAAICKAACGx5ISv1ekHEKduDrLQQ",\
                "BQACAgIAAxkBAAIw3mPI9OwqxpDKbmAvxY69opLh8yooAAIEKAACGx5ISnxQ36arIuqtLQQ",\
                "BQACAgIAAxkBAAIw4GPI9PpjpCtS0YuusfVeuhsZFLCCAAIHKAACGx5ISm54SOPB2-_yLQQ",\
                "BQACAgIAAxkBAAIw4mPI9d6MmSSubfgmCGgd5NI7Tu2LAAIWKAACGx5ISsUe1NFqeBOCLQQ",\
                "BQACAgIAAxkBAAIw5GPI9epo5oVcEG23DOO0cgQ0OQzqAAIXKAACGx5ISiTu5_xrAmPlLQQ",\
                "BQACAgIAAxkBAAIw5mPI9fbtlZEXVWT7KU9r59G5_xbFAAIYKAACGx5ISl_8BqueMnSeLQQ",\
                "BQACAgIAAxkBAAIw6GPI9gABtCvyA1S3Sbd8JouTcfuRyAACGSgAAhseSEo6dQuj4aIlCS0E",\
                "BQACAgIAAxkBAAIw6mPI9g2eFNzURRVixWshPbOTenQUAAIaKAACGx5ISh02R3LbARJoLQQ",\
                "BQACAgIAAxkBAAIw7GPI9kCZagbSRJuF4Jk3JiICSCN1AAIbKAACGx5ISnmf0MREH307LQQ",\
                "BQACAgIAAxkBAAIw7mPI9lQb1aavTmt4xdK0nBnXYvHSAAIdKAACGx5ISgsvq6MixB0KLQQ",\
                "BQACAgIAAxkBAAIw8GPI9mTNsr6ttykxfft1wGA2kgZEAAIeKAACGx5ISkVWh2Kqx3iSLQQ",\
                "BQACAgIAAxkBAAIxDGPJKDhy1QT7Quq3juVJbiZtqEV1AALHKQACGx5ISumu1_1o7k1LLQQ",\
                "BQACAgIAAxkBAAIxDmPJKGhD1NbnkvHykIsb2dwK7pnwAALIKQACGx5ISn1G37PJOXrYLQQ",\
                "BQACAgIAAxkBAAIxEGPJKIAhJH6OWi58JW0_KzKVFldNAALJKQACGx5IShxsnL7oNs_fLQQ",\
                "BQACAgIAAxkBAAIxEmPJKJc--fSMeRP6mi5BY7R5EbTwAALLKQACGx5IShLYaKsyCbrLLQQ",\
                "BQACAgIAAxkBAAIxFGPJKKlv6A1_YtpCFTjru4CsTWhWAALMKQACGx5ISq7JsLfqBjzXLQQ",\
                "BQACAgIAAxkBAAIxFmPJKMSOBcWhbTiz_mgNuRCzUKUGAALNKQACGx5ISoKzl64AAdC-6C0E",\
                "BQACAgIAAxkBAAIxGGPJKOI_5Nx_Qs4PTsUopCe6yecaAALQKQACGx5ISv9Y_WR3vvyCLQQ"]


class_1 = ["BQACAgIAAxkBAAIvA2PITb-4vnByiEZxhf-Ty3b__qnyAALYJQACGx5ISl9mTGP4dU4bLQQ", \
           "BQACAgIAAxkBAAIvBWPITfda7EmRYoVI_MCfMBGueJiaAALbJQACGx5ISjnG3eiy3KmPLQQ", \
            "BQACAgIAAxkBAAIvB2PITgt_HN8x4cmJsSGwleG28q8lAALdJQACGx5ISrbYiKTcQ4HVLQQ"]

class_2 = ["BQACAgIAAxkBAAIvC2PITjpFjmeNqjRQe6l-W96Q0wGXAALeJQACGx5ISmg_qJPxNBsCLQQ", \
           "BQACAgIAAxkBAAIvDWPITlSNXX-fm06700mBu9o0qAcmAALfJQACGx5ISpFnBA-81VsmLQQ", \
            "BQACAgIAAxkBAAIvD2PITn4-9Xs78ihyTtha9vHnyMetAALhJQACGx5ISsjBEkMsvNjLLQQ"]

class_3 = ["BQACAgIAAxkBAAIvEWPITsBEVea4Ogh0Mo6virkiy2jiAALjJQACGx5ISslnsmtDikntLQQ", \
           "BQACAgIAAxkBAAIvE2PITvO1UskG3KC8aBX4QLw0LMiHAALkJQACGx5ISiOtiaRtgPj7LQQ", \
           "BQACAgIAAxkBAAIvFWPITxMcD2JawfL-ME6vBbEvyKOeAALlJQACGx5ISgGV1qBHFQfBLQQ"]

class_4 = ["BQACAgIAAxkBAAIvF2PIT0XFWBJiv-IIgIo_ktHYhJ8HAALmJQACGx5ISv096YeXOD7TLQQ",\
           "BQACAgIAAxkBAAIvGWPIT3C-G5n7oXx7O2AoRhY051HJAALoJQACGx5ISmULsltfj8WULQQ"]

class_5 = ["BQACAgIAAxkBAAIvHWPIT5U_BYKpdbggicBoZzns02HAAALpJQACGx5ISkzqZ33GmB6RLQQ", \
           "BQACAgIAAxkBAAIvH2PIT6b93iBqlmuFIK7q6z7KOsq0AALqJQACGx5IStyn2ac8OQaoLQQ", \
           "BQACAgIAAxkBAAIvIWPIT9I0VT0bb4vrQXXQsJ5nOhj6AALtJQACGx5ISoxPwXjBwOAgLQQ", \
           "BQACAgIAAxkBAAIvI2PIT-2FW3cl_4Lm0sRlsouRFLPlAALuJQACGx5ISmRgNvPEX1J-LQQ", \
            "BQACAgIAAxkBAAIvI2PIT-2FW3cl_4Lm0sRlsouRFLPlAALuJQACGx5ISmRgNvPEX1J-LQQ", \
            "BQACAgIAAxkBAAIvJ2PIUGSHFmDt7PnAgUK9nvqvCsMuAALxJQACGx5ISqfuhmBbVvI_LQQ", \
            "BQACAgIAAxkBAAIvKWPIUIrcCy81vOoHhLXN6zlhvBV7AALyJQACGx5ISp0PXRDJJJPBLQQ"]

class_6 = ["BQACAgIAAxkBAAIvLWPIUOJjbSPocW0olkEnvTId0L32AAL3JQACGx5ISqaGUc0Pro-GLQQ", \
            "BQACAgIAAxkBAAIvL2PIUP4pJYtGhpu_XMh8b-3YZkY1AAL5JQACGx5ISst0uwUlnTNbLQQ", \
            "BQACAgIAAxkBAAIvMWPIURzTCuH7j8oGEfcn5-niBpI_AAL7JQACGx5ISnkbz7PugdQhLQQ", \
            "BQACAgIAAxkBAAIvM2PIUTEVbVsZeno9HBHs_Cu56tebAAL9JQACGx5ISl_h93UsbF3ALQQ", \
            "BQACAgIAAxkBAAIvNWPIUUrpCcCylPQYZDh4qWfuFPo2AAL_JQACGx5ISszF6wRZhAj0LQQ", \
            "BQACAgIAAxkBAAIvN2PIUWWEEGTc3lBu4h8Sas1o1GrCAAICJgACGx5ISj6hIRTbzud9LQQ", \
            "BQACAgIAAxkBAAIvOWPIUXm4_GkqcNQVVQTe6LAXwQgGAAIEJgACGx5IShfMWBiqHMUZLQQ", \
            "BQACAgIAAxkBAAIvO2PIUYuu1xgxQdmFjG9N2q9QnS_4AAIFJgACGx5ISlyNT25oBj_ILQQ", \
            "BQACAgIAAxkBAAIvPWPIUZZax94qrRRev02oBYSOGG3uAAIHJgACGx5ISoUoy3FBUG2ZLQQ", \
            "BQACAgIAAxkBAAIvP2PIUbw3T409G4vmHcBWuEUUkxWaAAIIJgACGx5ISqQtg5lxA7GrLQQ", \
            "BQACAgIAAxkBAAIvQWPIUcnKNQKZ05PXzhQn1JUlhKkAAwkmAAIbHkhKhWDjukjavmItBA"]

class_7 = ["BQACAgIAAxkBAAIvQ2PIUeeKgE9XVmwS1wZoIaMZeQRDAAILJgACGx5ISidhdo8coa_FLQQ", \
           "BQACAgIAAxkBAAIvRWPIUgX39rC3iDNPeVDFomhJGcxAAAIMJgACGx5ISiv_rjyL3AUaLQQ", \
           "BQACAgIAAxkBAAIvR2PIUhAfs3MgtnAiglu2nCRDPgoqAAINJgACGx5IStnwLHAGb6deLQQ", \
           "BQACAgIAAxkBAAIvSWPIUiyzkAYzYhzaxzcZTHQE75c-AAIOJgACGx5ISnF9nywKnS3ILQQ", \
            "BQACAgIAAxkBAAIvS2PIUk8vPWzcU5ooT9I24cxRwUvHAAIPJgACGx5ISrghPEZvab5OLQQ", \
            "BQACAgIAAxkBAAIvTWPIUmhpPyuvS0nBByP2VXKlJRoIAAIQJgACGx5ISmzIWf0vzjUTLQQ", \
            "BQACAgIAAxkBAAIvT2PIUpcUjwrgtMmkDcPB5SuA1p-CAAIRJgACGx5ISm8VcU2zyPTSLQQ", \
            "BQACAgIAAxkBAAIvUWPIUqUqf1LLaZmSQ5oEum9GvneJAAISJgACGx5ISvtMUISGtHaPLQQ", \
            "BQACAgIAAxkBAAIvU2PIUsgHhUYKH6cVX07SoSFikAnzAAITJgACGx5ISiaHaXlMhE7MLQQ", \
            "BQACAgIAAxkBAAIvVWPIUtrD-ccVFUQ4fSaopP_V25jnAAIUJgACGx5ISvyvls19M0xELQQ", \
            "BQACAgIAAxkBAAIvV2PIUv8uFNeF2AP7ldK7H7AJqhwhAAIVJgACGx5ISinlbURHy4kMLQQ", \
            "BQACAgIAAxkBAAIvWWPIUxaeG2qC5g0GKa-kQlhEECViAAIXJgACGx5IStaBDbIWi0LfLQQ", \
            "BQACAgIAAxkBAAIvW2PIUyhrLcU6WpLNLXabJLu9H-SgAAIYJgACGx5ISrZCfWMfoCaFLQQ", \
            "BQACAgIAAxkBAAIvXWPIUzVs59wfGuwSgWOgkdn8w4nbAAIZJgACGx5ISlg9M4NjdHcRLQQ"]

class_8 = ["BQACAgIAAxkBAAIvYWPIU1RRA5oU_wQfblstHvFyJx0HAAIbJgACGx5ISiYlsGM3aftzLQQ", \
           "BQACAgIAAxkBAAIvY2PIU3BSyWrV8HPN694mlN0a6mlwAAIdJgACGx5ISuopKRyoJgppLQQ", \
            "BQACAgIAAxkBAAIvZWPIU39jkKo-v1PuuMuKJhtdIyjaAAIeJgACGx5ISnS9Cm72-IlgLQQ", \
            "BQACAgIAAxkBAAIvZ2PIU6WdPlPl1dXCr0TC6UgXB2-_AAIgJgACGx5ISkLK80BYaFHPLQQ", \
            "BQACAgIAAxkBAAIvaWPIU7-bKgItMhbGmgUZgmVu2pg7AAIhJgACGx5ISv0QUFGXGrXILQQ", \
            "BQACAgIAAxkBAAIva2PIU9o9dUm3T4h9XH3gTZ39fgZOAAIiJgACGx5ISrGzs5SGGoAFLQQ", \
            "BQACAgIAAxkBAAIvbWPIVCfP8m42gyzfQsOfpSJlVByxAAInJgACGx5ISpiNW6m5oP2dLQQ", \
            "BQACAgIAAxkBAAIvb2PIVDGLSLUE59UJy0kbHQfgsNtBAAIoJgACGx5ISoSGbgTW_UNiLQQ"]

class_9 = ["BQACAgIAAxkBAAIvcWPIVFLf4FwyiY36qrk2qQxylx74AAIqJgACGx5IStWg1gy-BAebLQQ", \
            "BQACAgIAAxkBAAIvc2PIVHF_SOPmN9IrVMTQDhhcTDCpAAIrJgACGx5ISkD_p74V2xerLQQ", \
            "BQACAgIAAxkBAAIvdWPIVH8FmxfeUyaK1y6ywtRDu_W7AAIsJgACGx5ISkvA8dpmgZYwLQQ", \
            "BQACAgIAAxkBAAIvd2PIVJYCj2pYkiMkMRbfIOGZnBjnAAItJgACGx5ISgn9KRICBLiYLQQ", \
            "BQACAgIAAxkBAAIveWPIVKIUHQdX0Xj-Da8H1Z1DOjsdAAIuJgACGx5ISlkIsNipQ4WyLQQ"]

class_10 = ["BQACAgIAAxkBAAIve2PIVLi8S4LljJIZfwMgKEzqZ-LqAAIvJgACGx5ISp47gqT9kug7LQQ", \
            "BQACAgIAAxkBAAIvfWPIVNoKc4CjR8p2loJjPsiXIYbWAAIwJgACGx5ISt88TIqmx2OyLQQ"]

class_11 = ["BQACAgIAAxkBAAIvf2PIVO8DKLgsTKfgJB-92XMnQzFXAAIxJgACGx5ISozYcQGmVmXOLQQ", \
            "BQACAgIAAxkBAAIvgWPIVQTS5P7S1EOCK6z-ncZlLQNEAAIyJgACGx5ISpiCQgFX2E1WLQQ", \
            "BQACAgIAAxkBAAIvg2PIVWHBiiSfl512XVA8tL5zcDekAAI0JgACGx5ISkvEYBkiChK3LQQ", \
            "BQACAgIAAxkBAAIvhWPIVXhEgFmW_MU23RLid54pG4pTAAI1JgACGx5ISrfdTph3QSpcLQQ"]

dtm_19_uzb = ["BQACAgIAAxkBAAI1YWPOzmwnLlajD_ejPpx61XObgNTiAAJ6JgACR8t5SuvPpjCK64p-LQQ", \
        "BQACAgIAAxkBAAI1Y2POzoOm8Ore0p1g1HxMP9-SPdU1AAJ8JgACR8t5Sto9avdMUrnMLQQ", \
        "BQACAgIAAxkBAAI1ZWPOzpx1lNiMac3Gk3b9jWqkaoIQAAJ9JgACR8t5SgH42-Bq-VkAAS0E", \
        "BQACAgIAAxkBAAI1Z2POzrQ2KYqWAAGVqRdx9yABd7J87gACfiYAAkfLeUpWeeOhj_7DhC0E", \
        "BQACAgIAAxkBAAI1aWPOzvQ_G0GPSYstGJOVZKJQjKQkAAJ_JgACR8t5SqzL8oTb53l8LQQ", \
        "BQACAgIAAxkBAAI1a2POzwZkDruOvZeS3Z6eLLMgBxMmAAKAJgACR8t5SjxVvzKBr8zqLQQ", \
        "BQACAgIAAxkBAAI1b2POzxv3wPz07kerv1m4EC6zNEd4AAKCJgACR8t5SnxDxjBpp_rvLQQ", \
        "BQACAgIAAxkBAAI1cWPOz1n958lliAUY8unzET50xTIbAAKDJgACR8t5SjvTenLDfMe1LQQ", \
        "BQACAgIAAxkBAAI1dWPOz3EvuDQem1Pv2Y2dhNR6uLPyAAKFJgACR8t5SoEWFGsRTXGWLQQ", \
        "BQACAgIAAxkBAAI1eWPOz5PtwgHVI3l4XAZVLT7cDxODAAKIJgACR8t5StA1MVbgm0vBLQQ", \
        "BQACAgIAAxkBAAI1e2POz6YWXM6IpnfpN_neTbGdXCa3AAKJJgACR8t5SoM6s2XEonJxLQQ"]

dtm_19_rus = ["BQACAgIAAxkBAAI1fWPOz8LirKKvDZycWIYJMwR9ExbSAAKKJgACR8t5SvoPpM2Bt4kfLQQ", \
        "BQACAgIAAxkBAAI1f2POz9DLlRzGrQKJ4DoQ5RWI4tFIAAKLJgACR8t5Sm07PA_AxaciLQQ", \
        "BQACAgIAAxkBAAI1gWPOz-fFbORiZYBKOpO56PRy9PeIAAKMJgACR8t5SjcoYEOJkMqULQQ", \
        "BQACAgIAAxkBAAI1g2POz_KV7aeJl1T8BUtO6Ljt_uccAAKNJgACR8t5SsFrJ8-jQLRLLQQ"]

dtm_20_uzb = ["BQACAgIAAxkBAAI1hWPO0E_3c4vdwHcJOmH4Hz7A0jUmAAKRJgACR8t5SnPTrd5aaKSmLQQ", \
        "BQACAgIAAxkBAAI1h2PO0Fr1nX3w-hqaR2cwMW9J0c7LAAKUJgACR8t5SnfVJbLVt_gBLQQ", \
        "BQACAgIAAxkBAAI1iWPO0GYkXdaW8Ssd_3HHd7wjTe0CAAKWJgACR8t5Ske9SiHplNFyLQQ", \
        "BQACAgIAAxkBAAI1i2PO0HGY2dejnqBVFN2OWjpobMp4AAKYJgACR8t5SrxLEfW_yoAvLQQ", \
        "BQACAgIAAxkBAAI1jWPO0H28urxYHONa0xf6SJDM64D4AAKaJgACR8t5SoHSGcLesq7nLQQ", \
        "BQACAgIAAxkBAAI1j2PO0JIyKuVNFCafIlB19B6w7ocYAAKcJgACR8t5SpmMi9KqHxW6LQQ", \
        "BQACAgIAAxkBAAI1kWPO0J0TvI_Y0YWOQ-8JxV6cK5Z_AAKdJgACR8t5SrTncJNBit3rLQQ", \
        "BQACAgIAAxkBAAI1k2PO0L5jwl7ctXuoVTKcwiNZGcWgAAKeJgACR8t5SkMhitU6te-7LQQ", \
        "BQACAgIAAxkBAAI1lWPO0M3SmE1KH2ky2evifiyAfPlSAAKgJgACR8t5SilNKD52R9pZLQQ", \
        "BQACAgIAAxkBAAI1l2PO0Nn5c40nEsPrW4ltYWAKMkQ5AAKhJgACR8t5Skk4SzGOgM3lLQQ"]

dtm_20_rus = ["BQACAgIAAxkBAAI1mWPO0WLXyBk_6s-pAAGtmcZjmyyewwACoiYAAkfLeUpNDxPdi026cS0E", \
        "BQACAgIAAxkBAAI1m2PO0XOj9qDxtOmIT6Nk0Qgx9VQpAAKjJgACR8t5StCF9d8iEkZ2LQQ", \
        "BQACAgIAAxkBAAI1nWPO0YA9PqCo2g3MYRHWbKYpGpIGAAKkJgACR8t5SmLqjLV6U6CrLQQ", \
        "BQACAgIAAxkBAAI1n2PO0cV2LfNJOyRxabd5vq8CgNoDAAKpJgACR8t5Sqx4a0Kh-EfoLQQ", \
        "BQACAgIAAxkBAAI1oWPO0fQBnBj1B5siSNnxn_YqrXH7AAKsJgACR8t5SuEHonmnYytMLQQ", \
        "BQACAgIAAxkBAAI1o2PO0gABIgX9RMVcN5A8peO28dqj9wACrSYAAkfLeUrh1ay5zpwPxC0E", \
        "BQACAgIAAxkBAAI1pWPO0g2HqZz6i7Wp3Djhz95i6P9hAAKvJgACR8t5Sn35wGx3ZAywLQQ", \
        "BQACAgIAAxkBAAI1p2PO0hiD5TcAAc68a4ndy0cb8A6NwAACsSYAAkfLeUp_6KtgwqtE1y0E", \
        "BQACAgIAAxkBAAI1q2PO0jwqQfmi3aqhB3IlAtRtz2tqAAKzJgACR8t5SqwkSNfilSaSLQQ", \
        "BQACAgIAAxkBAAI1rWPO0ko39h9R8ryJxolEk4xy5Z1LAAK0JgACR8t5SpJr42HnIVahLQQ", \
        "BQACAgIAAxkBAAI1r2PO0lW-O7SZvPAOHNP8BYF1yaDXAAK3JgACR8t5StmNZxVzEkxeLQQ", \
        "BQACAgIAAxkBAAI1sWPO0mG7586EcZU_uq2bTBpuMBnxAAK6JgACR8t5SqT0yGTxksZ0LQQ", \
        "BQACAgIAAxkBAAI1s2PO0m0yQZAOg66BFSBECoxTxmZEAAK_JgACR8t5SnDkpS3D2eioLQQ", \
        "BQACAgIAAxkBAAI1tWPO0nca8upcRqaPYY7BjhTp-U6LAALEJgACR8t5SgkmG6Hf58iGLQQ"]

dtm_22_uzb = ["BQACAgIAAxkBAAI1t2PO0wM_yw5H-ogK5OZJa8iJv-mlAALpJgACR8t5SroBXYv809ELLQQ", \
        "BQACAgIAAxkBAAI1uWPO0xALq-eYA0EkR8ftdoL9uMxuAALqJgACR8t5SqGZLRazOp_CLQQ", \
        "BQACAgIAAxkBAAI1u2PO0yX3LYsXKV_x_mt_cpBN7adHAALrJgACR8t5ShBL0SUs7xn3LQQ", \
        "BQACAgIAAxkBAAI1vWPO0zJphGvEWl-PoKZs_e8AAYirGgAC7CYAAkfLeUqosoimpV4NHy0E", \
        "BQACAgIAAxkBAAI1v2PO0z67ei6KFNyGAmDEsJDrMF7IAALtJgACR8t5Sgl8XpZBQt2cLQQ", \
        "BQACAgIAAxkBAAI1wWPO00qqEeQDRHEdaLk5zh2IKHoQAALuJgACR8t5SuZJzWk1HchkLQQ", \
        "BQACAgIAAxkBAAI1w2PO01aFgNo53tg_BO0kDNzkY8eoAALxJgACR8t5SiN8O8KTk5SoLQQ", \
        "BQACAgIAAxkBAAI1xWPO02Kj8uTop_YhlVFJJRSSXkC1AAL1JgACR8t5SjgIzJv27MYvLQQ", \
        "BQACAgIAAxkBAAI1x2PO024ZwKLJJYzMm95v8aqOezvHAAL3JgACR8t5SoyGfXDzkVg8LQQ", \
        "BQACAgIAAxkBAAI1yWPO03mg2Naluv6A4frz3hl1jOBNAAL5JgACR8t5SkzM8aE6DCnpLQQ", \
        "BQACAgIAAxkBAAI1y2PO04bWi2_hhJt-Aktvan4vT3yhAAL9JgACR8t5SpHFClKAXS6uLQQ", \
        "BQACAgIAAxkBAAI1zWPO05IdP2tXzs3GJU9d7mK83uDrAAL-JgACR8t5Sl-jOdxLjSTKLQQ", \
        "BQACAgIAAxkBAAI1z2PO052mGC1d65Z0bZxvMrDR6E_0AAL_JgACR8t5SrJkGZvDf6CnLQQ", \
        "BQACAgIAAxkBAAI10WPO06frh80XE4FRbMPh5xjKBMvTAAIBJwACR8t5SgUFnDb9S7hZLQQ", \
        "BQACAgIAAxkBAAI102PO07KeSTh0SXJGbIRelXaotKgCAAICJwACR8t5SuA4bBO3sZYfLQQ", \
        "BQACAgIAAxkBAAI11WPO077NGJu4L6PM06WIXyJtc6e7AAIEJwACR8t5SvPG2qq7TPPWLQQ", \
        "BQACAgIAAxkBAAI112PO08vvAayu4KRD5AosbZAU_I4DAAIGJwACR8t5Sqcl3x7wM1IRLQQ", \
        "BQACAgIAAxkBAAI12WPO09Xxzvb1_C3plcjbes0_D8uSAAIHJwACR8t5Sna3o8pcR9LALQQ"]

dtm_22_rus = ["BQACAgIAAxkBAAI122PO1EkqdW203g7bS_5hvDWf7bjTAAILJwACR8t5Sh8U9_NkyAOtLQQ", \
        "BQACAgIAAxkBAAI13WPO1FbL6N7JPnkXuYHalrNkZp-fAAINJwACR8t5SosSCqytug3cLQQ", \
        "BQACAgIAAxkBAAI132PO1GOMuZ2ysNDAvY5CuYuRrVDwAAIOJwACR8t5SrQdLKOXSKEULQQ", \
        "BQACAgIAAxkBAAI14WPO1G8-0vn0IGTcJ70TRGs8RwozAAIPJwACR8t5SkOPpYIf5lAjLQQ", \
        "BQACAgIAAxkBAAI142PO1HpFHq-jVT3xTo2Hfdgg671BAAIQJwACR8t5SvsTMjM7X5p0LQQ", \
        "BQACAgIAAxkBAAI15WPO1IY5oaEpqsNPjSlwBCDQQ0-zAAIRJwACR8t5ShWcn1SsHo4VLQQ", \
        "BQACAgIAAxkBAAI152PO1JYYtDyRKXN_z8jmHJ2xcLxhAAISJwACR8t5Srl9_MKUaZw8LQQ", \
        "BQACAgIAAxkBAAI16WPO1KJAMsvLkU6O4JcWgS10rjOUAAITJwACR8t5SgpApV8d3qBiLQQ", \
        "BQACAgIAAxkBAAI162PO1K9laO_vbrXlEJZPgGniRZ63AAIUJwACR8t5Shv0hYN_sgMpLQQ", \
        "BQACAgIAAxkBAAI17WPO1LwV1DdD_Sq6PSHi_N1CZU5oAAIVJwACR8t5SiY3LN77eHhxLQQ", \
        "BQACAgIAAxkBAAI172PO1MgYq8sjayCzs7mxOetrYM-qAAIWJwACR8t5SrvdQv_AGZA-LQQ", \
        "BQACAgIAAxkBAAI18WPO1NWXmcbWoP0NdcVt9TGW38u0AAIXJwACR8t5SiGo8sBUiYlwLQQ", \
        "BQACAgIAAxkBAAI182PO1OhyjYYK5v0GH8vvQllWy6x_AAIZJwACR8t5ShxVdx8iQZqhLQQ", \
        "BQACAgIAAxkBAAI19WPO1PPDhtSramLEvMjQYKs1jKfAAAIaJwACR8t5SrCOe3365dydLQQ", \
        "BQACAgIAAxkBAAI192PO1P4MB-3ZwZ41OWGz-3GpL_S4AAIbJwACR8t5Su3PLIBOCL-bLQQ", \
        "BQACAgIAAxkBAAI1-WPO1Qx1-bHkLHTGlc8XmzydyyUtAAIcJwACR8t5SngI74QUnqOGLQQ", \
        "BQACAgIAAxkBAAI1-2PO1RgVwX_ga0a1LjhPoz26GRHuAAIdJwACR8t5SvfQCfHUZu0mLQQ", \
        "BQACAgIAAxkBAAI1_WPO1UkyIZ7UyS-jovBdTovCbwVoAAIeJwACR8t5SjILonwkfbuoLQQ", \
        "BQACAgIAAxkBAAI1_2PO1VUdnJJKhYZJNPlqvZ6b6VWnAAIfJwACR8t5SphEZVA3Scw7LQQ", \
        "BQACAgIAAxkBAAI2AWPO1V8kco3yehtCrqoulUULhlFCAAIgJwACR8t5Sgh-A86HsPQ6LQQ", \
        "BQACAgIAAxkBAAI2A2PO1WtaIs8RWlBZ4K82shjTISZ9AAIhJwACR8t5StwRKfapiDy8LQQ", \
        "BQACAgIAAxkBAAI2BWPO1Xcxh19sGK5muZt-N-KkuI3bAAIiJwACR8t5SmCVQt2zfu9CLQQ", \
        "BQACAgIAAxkBAAI2B2PO1YQo5wk0tlRJnZQ4ESDJVxDPAAIkJwACR8t5SjsVVIlyWYlzLQQ", \
        "BQACAgIAAxkBAAI2CWPO1Y9RaelSC-F8lB6AGURbQnFJAAIlJwACR8t5So2xHDmZjBPNLQQ", \
        "BQACAgIAAxkBAAI2C2PO1ZwJ4d7DLqvYP0KzUncefth1AAImJwACR8t5SoByopyWF5oQLQQ", \
        "BQACAgIAAxkBAAI2DWPO1ahx56ewnXIcefuqI7uO3A67AAInJwACR8t5SvdnB23knhYYLQQ", \
        "BQACAgIAAxkBAAI2D2PO1bP8-jmqmEGKvDBdRNYdIs8RAAIoJwACR8t5SocbahhyYRIeLQQ", \
        "BQACAgIAAxkBAAI2EWPO1cGpVdywmU-mcXERWRp3qzqxAAIpJwACR8t5Sn4TcO_V6qeVLQQ", \
        "BQACAgIAAxkBAAI2E2PO1c2LsIJcbWRkcpaERWpGKTmBAAIqJwACR8t5SpD3O5tlxeckLQQ", \
        "BQACAgIAAxkBAAI2FWPO1drbfdEkFB0vAAGk3mfr2pBeiQACKycAAkfLeUoFNuazDGvwdS0E", \
        "BQACAgIAAxkBAAI2F2PO1eTT6jKp2WBQApPjLCYFRcrkAAIsJwACR8t5Si1A4cDBNc4-LQQ", \
        "BQACAgIAAxkBAAI2GWPO1fGzQROi94c9DXQ8vXz-0WaPAAItJwACR8t5Sq_gVb0UQUnNLQQ", \
        "BQACAgIAAxkBAAI2G2PO1gABBTIvdZPxXF3sdH94cg8wtgACLicAAkfLeUoHKzuDirx28i0E", \
        "BQACAgIAAxkBAAI2HWPO1g94qsg4CEo202RTzF8knXLKAAIvJwACR8t5SsgFvsEtzE13LQQ", \
        "BQACAgIAAxkBAAI2H2PO1lam4EK8nUWdWIKJ5lO_yssLAAIwJwACR8t5SjrsyfdPrfWgLQQ", \
        "BQACAgIAAxkBAAI2IWPO1mK_iXjiBx2dyigh1Oe8QsX2AAIxJwACR8t5Stp71eQ7punxLQQ", \
        "BQACAgIAAxkBAAI2I2PO1m3qyfKAQ4-877XVaeRYvq1lAAIyJwACR8t5SvwXaT3iFYMDLQQ", \
        "BQACAgIAAxkBAAI2JWPO1njknApThMoGIrhsKmswnjPqAAIzJwACR8t5Sn5sEy0VGDCQLQQ", \
        "BQACAgIAAxkBAAI2J2PO1oTrLQ1Gp16UoW4wlqXZ82HzAAI0JwACR8t5Sqr6NPut27_iLQQ"]

olimpiada_books_uzb = ["BQACAgIAAxkBAAJBhmQ-4bbwCSJEZ8sPEWsyw3k8_XwmAAIBLgAC5tb5SbyHJUO66QHALwQ",\
                       "BQACAgIAAxkBAAJBiGQ-4dHeF8vv2FhtKqiXA6BC2sOeAAICLgAC5tb5SXzXlQT61DnZLwQ",\
                       "BQACAgIAAxkBAAJBimQ-4eMyMkzZRAABzbfiZajHx-PQZwACAy4AAubW-UnmlxbMm8VaXy8E",\
                       "BQACAgIAAxkBAAJBjGQ-4fejPsSHFL-adrr3fEqygj66AAIELgAC5tb5SdmQnIB-N2OiLwQ",\
                       "BQACAgIAAxkBAAJBkGQ-4hgQ_AQ_dUuGgzF50LD6A-bLAAIFLgAC5tb5SVkzlqztLkL0LwQ",\
                       "BQACAgIAAxkBAAJBkmQ-4jDMqOZJabNYuitSTGhsS-XEAAIGLgAC5tb5SYpRJRVuWILxLwQ",\
                       "BQACAgIAAxkBAAJBlGQ-4kBov1ZcPCI5DnKfxcbqnfxeAAIHLgAC5tb5SdW2I1ImkvDjLwQ",\
                       "BQACAgIAAxkBAAJBlmQ-4k2io7Iy6lGWCHra8h0FrW-BAAIKLgAC5tb5Sbip59cKuNXZLwQ",\
                       "BQACAgIAAxkBAAJBmGQ-4lyt_ldmq1Hp1FQ721eTPDvxAAIMLgAC5tb5Sd3IuGtTFJopLwQ",\
                       "BQACAgIAAxkBAAJBmmQ-4nW46fU4NWzwlvY3onyOX6XPAAIOLgAC5tb5SalKpxxB8-8aLwQ"]

olimpiada_books_rus = ["BQACAgIAAxkBAAJBnmQ-47QOzEaHszOTGARYfmIC5xFMAAIRLgAC5tb5SUGpB9tpy8w6LwQ",\
                       "BQACAgIAAxkBAAJBoGQ-48kY4o0mYxcWdE6R0nDtu3mTAAITLgAC5tb5SWtG_EnRWuJqLwQ",\
                       "BQACAgIAAxkBAAJBomQ-4969MRlTqMAPZeLv7rZEJ8D4AAIULgAC5tb5SaJH2jj1vMSqLwQ",\
                       "BQACAgIAAxkBAAJBpGQ-4_dD96sW1SpgMgbnHDmxznUgAAIVLgAC5tb5SSGjFljdJm_VLwQ",\
                       "BQACAgIAAxkBAAJBpmQ-5Ao2JYo0p1O3qzJ4XgjOH_QDAAIWLgAC5tb5ScDib65wFmlqLwQ",\
                       "BQACAgIAAxkBAAJBqGQ-5B1qwqNi6k7d7mUgTxqjsbVYAAIXLgAC5tb5SbpF7ShnBbk1LwQ",\
                       "BQACAgIAAxkBAAJBqmQ-5CnRaDyDHT7ONwdSOjlFtkQmAAIYLgAC5tb5SdD_Q3cEYEwwLwQ"]