from . import wiut_years_handler
from . import amity_years_handler
from . import bmu_years_handler
from . import gubkina_years_handler
from . import iut_years_handler
from . import lomonosova_years_handler
from . import mifi_years_handler
from . import national_years_handler
from . import plehanova_years_handler