from . import main_keyboard
from . import univers_1
from . import univers_2
from . import univers_3
from . import library
from . import uzbek_books
from . import russian_books
from . import dtm
from . import lyceums
from . import contact_taker